# Generated by Django 4.1.3 on 2022-12-06 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=4)),
                ("catalog_number", models.CharField(max_length=4)),
                ("instructor", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=4)),
                ("course_number", models.CharField(max_length=10)),
                ("description", models.TextField(default="")),
            ],
            options={
                "unique_together": {
                    (
                        "subject",
                        "catalog_number",
                        "instructor",
                        "section",
                        "course_number",
                        "description",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="Departments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        default="Author of this post chose to be anonymous",
                        max_length=30,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        default="No topic was provided by the author of this post",
                        max_length=100,
                    ),
                ),
                ("startDate", models.DateField(default="2022-12-06")),
                ("endDate", models.DateField(default="2022-12-13")),
                (
                    "description",
                    models.TextField(
                        default="No description was provided by the author of this post"
                    ),
                ),
                ("post_type", models.TextField(default="section")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studybuddy.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.CharField(
                        default="", max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("major", models.CharField(default="", max_length=50)),
                ("zoomLink", models.URLField(default="", max_length=300)),
                ("blurb", models.TextField(default="")),
                ("username", models.CharField(default="", max_length=30)),
                ("friends", models.ManyToManyField(to="studybuddy.user")),
            ],
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("name", models.CharField(default="Study Session", max_length=50)),
                ("date", models.DateField(default="12-06-2022")),
                ("start", models.TimeField(default="03-01")),
                ("end", models.TimeField(default="04-01")),
                ("accepted", models.CharField(default="?", max_length=4)),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studybuddy.post",
                    ),
                ),
                ("users", models.ManyToManyField(to="studybuddy.user")),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studybuddy.post",
                    ),
                ),
                ("users", models.ManyToManyField(to="studybuddy.user")),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="studybuddy.user"
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="studybuddy.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="studybuddy.user",
                    ),
                ),
            ],
            options={"ordering": ("date_added",),},
        ),
        migrations.CreateModel(
            name="Friend_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("declined", models.TextField(verbose_name="no")),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_user",
                        to="studybuddy.user",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_user",
                        to="studybuddy.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrolledClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studybuddy.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studybuddy.user",
                    ),
                ),
            ],
        ),
    ]
