# Generated by Django 4.1.3 on 2022-12-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="04-02"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="03-02"),
        ),
    ]
