# Generated by Django 4.1.3 on 2022-12-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0002_alter_studysession_end_alter_studysession_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="04-12"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="03-12"),
        ),
    ]
