# Generated by Django 4.1.3 on 2022-12-06 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0003_user_image_alter_studysession_end_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="course", unique_together=None,),
        migrations.DeleteModel(name="Departments",),
        migrations.RemoveField(model_name="enrolledclass", name="course",),
        migrations.RemoveField(model_name="enrolledclass", name="student",),
        migrations.RemoveField(model_name="friend_request", name="from_user",),
        migrations.RemoveField(model_name="friend_request", name="to_user",),
        migrations.RemoveField(model_name="message", name="room",),
        migrations.RemoveField(model_name="message", name="user",),
        migrations.RemoveField(model_name="post", name="course",),
        migrations.RemoveField(model_name="post", name="user",),
        migrations.RemoveField(model_name="room", name="post",),
        migrations.RemoveField(model_name="room", name="users",),
        migrations.RemoveField(model_name="studysession", name="post",),
        migrations.RemoveField(model_name="studysession", name="users",),
        migrations.RemoveField(model_name="user", name="friends",),
        migrations.DeleteModel(name="Course",),
        migrations.DeleteModel(name="EnrolledClass",),
        migrations.DeleteModel(name="Friend_Request",),
        migrations.DeleteModel(name="Message",),
        migrations.DeleteModel(name="Post",),
        migrations.DeleteModel(name="Room",),
        migrations.DeleteModel(name="StudySession",),
        migrations.DeleteModel(name="User",),
    ]
