# Generated by Django 4.1.1 on 2023-02-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0006_alter_post_enddate_alter_post_startdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="end",
            field=models.TimeField(default="20-02"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start",
            field=models.TimeField(default="19-02"),
        ),
    ]
